workflows:
  android_debug:
    name: Android Debug
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Hazırlık
        script: |
          flutter --version
          flutter doctor -v
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi
          chmod +x android/gradlew || true
          flutter pub get
      - name: Build (detaylı log)
        script: |
          set -o pipefail
          flutter clean
          flutter build apk --debug -v | tee build_log.txt
      - name: Hata özeti
        script: |
          if grep -q "FAILURE: Build failed with an exception." build_log.txt; then
            echo "======= HATA ÖZETİ ======="
            awk '/FAILURE: Build failed with an exception./{flag=1} flag{print} /BUILD FAILED/{flag=0}' build_log.txt | tail -n 140 || true
            echo "=========================="
            exit 1
          fi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
