workflows:
  debug_apk:
    name: Android Debug APK (safe patch)
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Flutter version & doctor
        script: |
          flutter --version
          flutter doctor -v
      - name: Accept Android SDK licenses
        script: yes | sdkmanager --licenses || true
      - name: Create android/local.properties
        script: |
          mkdir -p android
          echo "flutter.sdk=/Users/builder/programs/flutter" > android/local.properties
          echo "sdk.dir=/usr/local/share/android-sdk" >> android/local.properties
      - name: Patch Android embedding (v2) and package path
        script: |
          set -e
          APP_DIR="android/app"
          SRC_OLD="$APP_DIR/src/main/kotlin/com/example/derin_barkod/MainActivity.kt"
          SRC_NEW_DIR="$APP_DIR/src/main/kotlin/com/derinwifi/barkod"
          SRC_NEW="$SRC_NEW_DIR/MainActivity.kt"
          MANIFEST="$APP_DIR/src/main/AndroidManifest.xml"

          mkdir -p "$SRC_NEW_DIR"

          printf '%s\n'             'package com.derinwifi.barkod'             ''             'import io.flutter.embedding.android.FlutterActivity'             ''             'class MainActivity : FlutterActivity()' > "$SRC_NEW"

          if [ -f "$SRC_OLD" ]; then
            rm -f "$SRC_OLD"
          fi

          if [ -f "$MANIFEST" ] && ! grep -q 'android:name="flutterEmbedding"' "$MANIFEST"; then
            awk '
              /<\/application>/ && !done {
                print "        <meta-data android:name=\"flutterEmbedding\" android:value=\"2\" />"
                done=1
              }
              { print }
            ' "$MANIFEST" > "$MANIFEST.tmp" && mv "$MANIFEST.tmp" "$MANIFEST"
          fi
      - name: (Optional) Write google-services.json if CM_GOOGLESERVICES_JSON is set
        script: |
          if [ -n "${CM_GOOGLESERVICES_JSON:-}" ]; then
            echo "$CM_GOOGLESERVICES_JSON" | base64 --decode > android/app/google-services.json
            echo "google-services.json written."
          else
            echo "CM_GOOGLESERVICES_JSON not set. Skipping Firebase."
          fi
      - name: Fetch packages
        script: flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
