workflows:
  android_debug:
    name: Android Debug
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Create android folder if missing & get deps
        script: |
          echo "Flutter version:"
          flutter --version
          if [ ! -d "android" ]; then
            echo "android/ yok, oluşturuluyor..."
            flutter create --platforms=android .
          fi
          flutter pub get
      - name: Build debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
