      - name: Çıktı ağaçlarını listele
        script: |
          echo "=== build/app/outputs içeriği ==="
          (ls -R build/app/outputs || true)
          echo "=== android/app/build/outputs içeriği (gradle yol) ==="
          (ls -R android/app/build/outputs || true)

      - name: APK'leri topla (tüm muhtemel yollar)
        script: |
          mkdir -p artifacts
          # Flutter tek-variant yolu
          cp -f build/app/outputs/flutter-apk/*.apk artifacts/ 2>/dev/null || true
          # Gradle çoklu-variant/flavor yolu
          cp -f android/app/build/outputs/apk/**/*.apk artifacts/ 2>/dev/null || true
          cp -f android/app/build/outputs/apk/*.apk artifacts/ 2>/dev/null || true
          # Her ihtimale karşı tüm outputs'tan tara
          find build -type f -name "*.apk" -maxdepth 6 -print -exec cp -f {} artifacts/ \; || true
          # Bulunamadıysa anlamlı mesaj ver
          if [ -z "$(ls -A artifacts/*.apk 2>/dev/null)" ]; then
            echo "APK bulunamadı. Muhtemelen build düşmüş ya da variant ismi farklı."
            echo "Yukarıdaki 'ls -R' çıktılarında gerçek yolu görüp artifacts kalıbını genişletelim."
          else
            echo "Toplanan APK'ler:"
            ls -lh artifacts/*.apk
          fi
